apiVersion: v1
kind: Namespace
metadata:
  name: ops
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deletenses.Praveen.alpha.coveros.com
  namespace: ops
spec:
  group: Praveen.alpha.coveros.com
  names:
    kind: DeleteNs
    listKind: DeleteNsList
    plural: deletenses
    singular: deletens
  scope: Namespaced
  version: v1alpha1

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: delete-ns-operator
rules:
- apiGroups:
  - Praveen.alpha.coveros.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods/portforward
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - namespaces
  verbs:
  - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-ns
  namespace: ops
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: delete-ns-operator
subjects:
- kind: ServiceAccount
  name: delete-ns
  namespace: ops
roleRef:
  kind: ClusterRole
  name: delete-ns-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-ns-with-helm
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: delete-ns-operator
  template:
    metadata:
      labels:
        name: delete-ns-operator
    spec:
      serviceAccountName: delete-ns
      containers:
        - name: delete-ns-operator
          image: agill17/delete-ns-operator-new:v1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - delete-ns-operator
          imagePullPolicy: Always
          env:
            - name: RESYNC_PERIOD
              value: "10"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "delete-ns-operator"
