apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-ns-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: delete-ns-operator
  template:
    metadata:
      labels:
        name: delete-ns-operator
    spec:
      containers:
        - name: delete-ns-operator
          image: agill17/delete-ns-operator-new:v1.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - delete-ns-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "delete-ns-operator"
